/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(decode.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(db0cf2b7721ea37bdb16669e35469ec6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lora/decode.h>
// pydoc.h is automatically generated in the build directory
#include <decode_pydoc.h>

void bind_decode(py::module& m)
{

    using decode = gr::lora::decode;


    py::class_<decode, gr::block, gr::basic_block, std::shared_ptr<decode>>(
        m, "decode", D(decode))

        .def(py::init(&decode::make),
             py::arg("spreading_factor"),
             py::arg("header"),
             py::arg("payload_len"),
             py::arg("code_rate"),
             py::arg("crc"),
             py::arg("low_data_rate"),
             D(decode, make))


        ;
}
