/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(demod.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ddec7812177c7098f42f36410f81b81c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lora/demod.h>
// pydoc.h is automatically generated in the build directory
#include <demod_pydoc.h>

void bind_demod(py::module& m)
{

    using demod = gr::lora::demod;


    py::class_<demod, gr::block, gr::basic_block, std::shared_ptr<demod>>(
        m, "demod", D(demod))

        .def(py::init(&demod::make),
             py::arg("spreading_factor"),
             py::arg("header"),
             py::arg("payload_len"),
             py::arg("cr"),
             py::arg("crc"),
             py::arg("low_data_rate"),
             py::arg("beta"),
             py::arg("fft_factor"),
             py::arg("peak_search_algorithm"),
             py::arg("peak_search_phase_k"),
             py::arg("fs_bw_ratio"),
             D(demod, make))


        ;
}
