/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(detect.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(57e4599693fdb9838b1a7e9a6c20445e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lora/detect.h>
// pydoc.h is automatically generated in the build directory
#include <detect_pydoc.h>

void bind_detect(py::module& m)
{

    using detect = gr::lora::detect;


    py::class_<detect, gr::block, gr::basic_block, std::shared_ptr<detect>>(
        m, "detect", D(detect))

        .def(py::init(&detect::make),
             py::arg("spreading_factor"),
             py::arg("beta"),
             py::arg("fft_factor"),
             py::arg("peak_search_algorithm"),
             py::arg("peak_search_phase_k"),
             py::arg("fs_bw_ratio"),
             py::arg("on_length"),
             py::arg("filename_template"),
             D(detect, make))


        ;
}
