/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(encode.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(54e2e03df68d3149fddcfeca37933a78) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lora/encode.h>
// pydoc.h is automatically generated in the build directory
#include <encode_pydoc.h>

void bind_encode(py::module &m)
{

    using encode = gr::lora::encode;

    py::class_<encode, gr::block, gr::basic_block, std::shared_ptr<encode>>(
        m, "encode", D(encode))

        .def(py::init(&encode::make), py::arg("spreading_factor"),
             py::arg("code_rate"), py::arg("crc"), py::arg("low_data_rate"),
             py::arg("header"), D(encode, make))

        ;
}
