/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mod.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(79729e8233d4c049cd2ed7ab199128ba)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lora/mod.h>
// pydoc.h is automatically generated in the build directory
#include <mod_pydoc.h>

void bind_mod(py::module& m)
{

    using mod = gr::lora::mod;


    py::class_<mod, gr::block, gr::basic_block, std::shared_ptr<mod>>(m, "mod", D(mod))

        .def(py::init(&mod::make),
             py::arg("spreading_factor"),
             py::arg("d_sync_word"),
             D(mod, make))


        ;
}
