/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pyramid_demod.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2180045b1980cd48edfc4b2df4a993a4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lora/pyramid_demod.h>
// pydoc.h is automatically generated in the build directory
#include <pyramid_demod_pydoc.h>

void bind_pyramid_demod(py::module& m)
{

    using pyramid_demod = gr::lora::pyramid_demod;


    py::class_<pyramid_demod, gr::block, gr::basic_block, std::shared_ptr<pyramid_demod>>(
        m, "pyramid_demod", D(pyramid_demod))

        .def(py::init(&pyramid_demod::make),
             py::arg("spreading_factor"),
             py::arg("low_data_rate"),
             py::arg("beta"),
             py::arg("fft_factor"),
             py::arg("threshold"),
             py::arg("fs_bw_ratio"),
             D(pyramid_demod, make))


        ;
}
