/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(weak_demod.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0a271bf030d6bd75de10b2a97531b5c4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lora/weak_demod.h>
// pydoc.h is automatically generated in the build directory
#include <weak_demod_pydoc.h>

void bind_weak_demod(py::module& m)
{

    using weak_demod = gr::lora::weak_demod;


    py::class_<weak_demod, gr::block, gr::basic_block, std::shared_ptr<weak_demod>>(
        m, "weak_demod", D(weak_demod))

        .def(py::init(&weak_demod::make),
             py::arg("spreading_factor"),
             py::arg("header"),
             py::arg("payload_len"),
             py::arg("cr"),
             py::arg("crc"),
             py::arg("low_data_rate"),
             py::arg("d_sym_num"),
             py::arg("beta"),
             py::arg("fft_factor"),
             py::arg("peak_search_algorithm"),
             py::arg("peak_search_phase_k"),
             py::arg("fs_bw_ratio"),
             D(weak_demod, make))


        ;
}
